#!/bin/bash
#This is 100% the work of slowhawkeclipse on the ZFS Discord.
#User: https://discourse.practicalzfs.com/u/slowhawkeclipse/summary
#Thread: https://discourse.practicalzfs.com/t/sanoid-monitoring-bash-script-advice/1849

/usr/sbin/sanoid --monitor-snapshots
sleep 600

# Define the log file
LOGFILE="/where/you/want/your/logfile.log"

# Function to log the outputs with a timestamp
log_output() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOGFILE"
}

# Run the commands and store their outputs
output_snapshots=$(/usr/sbin/sanoid --monitor-snapshots)
output_capacity=$(/usr/sbin/sanoid --monitor-capacity)
output_health=$(/usr/sbin/sanoid --monitor-health)

# Log the outputs with timestamps
log_output "Snapshot Check: $output_snapshots"
log_output "Capacity Check: $output_capacity"
log_output "Health Check: $output_health"

# Concatenate outputs
output_all=$output_snapshots $output_capacity $output_health

# Check if all outputs start with "OK"
if [[ $output_snapshots == OK* ]] && [[ $output_capacity == OK* ]] && [[ $output_health == OK* ]]; then
  # If all checks are OK, ping healthchecks
  curl -m 10 --retry 5 https://ping.url
  log_output "All checks are OK. Healthcheck pinged successfully."
else
  echo "One or more checks did not return OK."
  curl -fsS -m 10 --retry 5 --data-raw "$output_all" https://ping.url/fail

  log_output "One or more checks did not return OK. Failure ping sent."
fi
